### ISSUE TITLE
Startup Error when not using MySQL

### ISSUE THREAD

**Issue by quorn23** [Rokas111/NewsPlus#2]
Hi,

the latest version produces a startup error, as i don't use MySql.

[https://pastebin.com/UqyBRpvT](https://pastebin.com/UqyBRpvT)

news.yml
`show-latest-news-on-join: true`
`show-latest-news-one-time-only: true`
`latest-news-one-time-only-use-mysql: false`

The MySQL,yml is the default created one as i didn't touch it.

**Comment by Rokas111** [comment]
**Fixed!**
